var categories = [
	"Abs. autorisée non rémunérée",
	"Absc non autoriséee non payée",
	"Absence autorisée MEH",
	"Absence autorisée MEH RQTH",
	"Accident de trajet",
	"Accident de travail",
	"Avant-vente",
	"Bénéficiaire don de congé",
	"Compl temps partiel / activite",
	"Congé administratif",
	"Congé CIF non rémunéré",
	"Congé CIF rémunéré",
	"Congé conseiller prud\'homale",
	"Congé d\'accompagnement",
	"Congé de parentalité non payé",
	"Congé de parentalité payé",
	"Congé de paternité",
	"Congé déménagement",
	"Congé enfant malade",
	"Congé examen prénatal",
	"Congé mariage/PACS",
	"Congé mariage/PACS enfant",
	"Congé militaire",
	"Congé naissance enfant",
	"Congé pour décès famille",
	"Congé pour examen / etudes",
    "Congé pour juré/témoin",
	"Congé recherche d\'emploi",
	"Congé sans solde",
	"Congé solidarité familiale",
	"Dispense Spe Rem",
	"Elu d\'état",
	"Enfant malade Alsace-Moseille",
	"Formation",
	"Formation Animation",
	"Formation mandat (CFESS IRP)",
	"Formation syndicale (CFESS)",
	"Général et administration",
	"Grossesse patho. post-natale",
	"Grossesse patho. pré-natale",
	"Heures déplacements récup",
	"Jour férié",
	"Jours CET",
	"Maladie",
	"Maladie professionnelle",
	"PDPMA",
	"Repos Hebdo/Quotidien",
	"Retour progressif au travail",
	"RTT non payée (Q2)",
	"RTT Q1",
	"Survenance handicap enfant",
	"Temps compensatoire",
	"Travaux passagers",
    "Vacances (Congés payés)"
];
var days = ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"];
var locations = [
	{ value: 'O', label: 'CGI' },
    { value: 'C', label: 'Client' },
    { value: 'T', label: 'Télétravail' },
    { value: 'NA', label: 'N/A' },
];