let categories = {
	fr: [
		"Abs. autorisée non rémunérée",
		"Absc non autoriséee non payée",
		"Absence autorisée MEH",
		"Absence autorisée MEH RQTH",
		"Accident de trajet",
		"Accident de travail",
		"Avant-vente",
		"Bénéficiaire don de congé",
		"Compl temps partiel / activite",
		"Congé administratif",
		"Congé CIF non rémunéré",
		"Congé CIF rémunéré",
		"Congé conseiller prud\'homale",
		"Congé d\'accompagnement",
		"Congé de parentalité non payé",
		"Congé de parentalité payé",
		"Congé de paternité",
		"Congé déménagement",
		"Congé enfant malade",
		"Congé examen prénatal",
		"Congé mariage/PACS",
		"Congé mariage/PACS enfant",
		"Congé militaire",
		"Congé naissance enfant",
		"Congé pour décès famille",
		"Congé pour examen / etudes",
		"Congé pour juré/témoin",
		"Congé recherche d\'emploi",
		"Congé sans solde",
		"Congé solidarité familiale",
		"Dispense Spe Rem",
		"Elu d\'état",
		"Enfant malade Alsace-Moseille",
		"Formation",
		"Formation Animation",
		"Formation mandat (CFESS IRP)",
		"Formation syndicale (CFESS)",
		"Général et administration",
		"Grossesse patho. post-natale",
		"Grossesse patho. pré-natale",
		"Heures déplacements récup",
		"Jour férié",
		"Jours CET",
		"Maladie",
		"Maladie professionnelle",
		"PDPMA",
		"Repos Hebdo/Quotidien",
		"Retour progressif au travail",
		"RTT non payée (Q2)",
		"RTT Q1",
		"Survenance handicap enfant",
		"Temps compensatoire",
		"Travaux passagers",
		"Vacances (Congés payés)"
	],
	en: [
		"Accident on the way to work Lv",
		"Accompaniment Leave",
		"Administrative Leave",
		"Authorized Absence MEH",
		"Authorized Absence MEH RQTH",
		"Authorized Unpaid Absence",
		"Bench",
		"Beneficiary Vac Donation Lv",
		"Bereavement Leave",
		"CET Leave",
		"Care of Child (Alsace-Moselle)",
		"Care of child",
		"Compensatory Time",
		"Daily / Weekly rest",
		"Education Leave (Paid)",
		"Education Leave (Unpaid)",
		"Exam/Study Leave",
		"Family Member Marriage",
		"Family Support Leave",
		"General and administration",
		"Grad Return to Work Off Days",
		"Handicap Child Announcement Lv",
		"Hours traveled recovered",
		"Job Search Leave",
		"Jury Duty Leave",
		"Labor Court Advise Leave",
		"Learning",
		"Learning animation",
		"Leave Without Pay",
		"Marriage Leave",
		"Military Leave",
		"Paid Parental Leave",
		"Paid special dispensation",
		"Paternity Birth Leave",
		"Paternity Leave",
		"Political Mandate Leave",
		"Postnatal Pathological Leave",
		"Prenatal Exam/Course",
		"Prenatal Pathological Leave",
		"Professional Illness Leave",
		"Proposal activity",
		"Public holiday",
		"Q2 Leave",
		"RTT Leave",
		"Relocation Leave",
		"Reproduction Protocol Leave",
		"Sick Leave",
		"Supplement part time/activity",
		"Unauthorized/Unpaid Leave",
		"Union Related Training Leave",
		"Union Training Leave",
		"Unpaid Parental Leave",
		"Vacation",
		"Work Injury Leave"
	]
}

let locations = [
	{ value: 'NA', label: 'N/A' },
	{ value: 'O', label: 'CGI' },
	{ value: 'C', label: 'Client' },
	{ value: 'T', label: 'Télétravail' },
]

let days = [
	{ num: 0, label: "sun" },
	{ num: 1, label: "mon" },
	{ num: 2, label: "tue" },
	{ num: 3, label: "wed" },
	{ num: 4, label: "thu" },
	{ num: 5, label: "fri" },
	{ num: 6, label: "sat" }
]
